### ISSUE TITLE
test_redis() hangs on python 3.x

### ISSUE THREAD

**Issue by shaunvxc** [shaunvxc/pytchfork#2]
Need to look into this

**Comment by mbertucci35** [comment]
What am i looking into?

**Comment by shaunvxc** [comment]
Fixed it!  Python 3 was treating my unicode sentinels as byte strings.  Needed to strictly encode them  at the beginning of my tests if running python 3.  Tests are working for all versions of python 3 now.

**Comment by mbertucci35** [comment]
Lol the Pytchfork/.  Clever spelling

**Comment by mbertucci35** [comment]
Python Pytchfork
